### ISSUE TITLE
Having Issues with the Boid Game.

### ISSUE THREAD

**Issue by SirHawbly** [Widdershin/old-game-maker-games#1]
I imported the files required, and I am getting an error about a gui.text that I cannot find (its in the oControl object and near the bottom of the draw file. 
Thanks.

**Comment by Widdershin** [comment]
Hey @silversteinrulz, I just added the missing gui.txt. You should be able to run the Boids project now.

Let me know if that doesn't work, then I can at least give you a prebuilt version.

**Comment by SirHawbly** [comment]
I'll check it out now, thanks so much.

**Comment by SirHawbly** [comment]
Now I'm getting a missing script error, oControl, line 32, execute_file.

**Comment by Widdershin** [comment]
I haven't yet had the chance to run Game Maker to attempt to figure out this issue, so in the meantime, here's a prebuilt version of Boids I have lying around:

https://www.dropbox.com/s/7z2g5uwe1v7xsqj/Boids.exe?dl=0

**Comment by SirHawbly** [comment]
Alright, remember to import it if you use the newer game maker. 
Thanks, Chris.
